// Code generated by goctl. DO NOT EDIT.
package types

type AdminSetAdRequest struct {
	Token   string `from:"token"`
	Owner   string `form:"owner"`
	Name    string `form:"name"`
	Content string `form:"content"`
	SiteUrl string `form:"site_url"`
}

type AdminSetAdReply struct {
	BasicReply
}

type CheckCostRequest struct {
	Token string `from:"token"`
	AdId  int64  `from:"ad_id"`
}

type CheckCostReply struct {
	Cost int64 `json:"cost"`
	BasicReply
}

type AdListRequest struct {
	Token string `form:"token"`
}

type AdListReply struct {
	BasicReply
	AdList []Ad `json:"ad_list"`
}

type AdInfoRequest struct {
	AdId  int64  `form:"ad_id"`
	Token string `form:"token"`
}

type AdInfoReply struct {
	BasicReply
	Ad Ad `json:"ad"`
}

type SendAdRequest struct {
	Token string `from:"token"`
}

type SendAdReply struct {
	BasicReply
	Ad Ad `json:"ad"`
}

type ClickAdRequest struct {
	AdId  int64  `from:"ad_id"`
	Token string `from:"token"`
}

type ClickAdReply struct {
	BasicReply
}

type BasicReply struct {
	Code int64  `json:"status_code"`
	Msg  string `json:"status_msg"`
}

type User struct {
	Id           int64  `json:"id"`
	Name         string `json:"name"`
	Collage      string `json:"collage"`
	AvatarUrl    string `json:"avatar_url"`
	Sex          int64  `json:"sex"`
	Point        int64  `json:"point"`
	CharacterUrl string `json:"character_url"`
}

type Admin struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type Student struct {
	Name    string `json:"name"`
	Collage string `json:"collage"`
	IdCard  string `json:"id_card"`
}

type Task struct {
	Id          int64  `json:"id"`
	UserId      string `json:"user_id"`
	Title       string `json:"title"`
	Type        int64  `json:"type"`
	Text        string `json:"text"`
	QuestionUrl string `json:"question_url"`
	AnswerUrl   string `json:"answer_url"`
	Bonus       int64  `json:"bonus"`
	State       int64  `json:"state"`
}

type Ad struct {
	Id       int64  `json:"id"`
	Owner    string `json:"owner"`
	Name     string `json:"name"`
	Content  string `json:"content"`
	ImageUrl string `json:"image_url"`
	SiteUrl  string `json:"site_url"`
	Target   Target `json:"target"`
}

type Target struct {
	District string `json:"district"`
	Sex      string `json:"sex"`
	Collage  string `json:"collage"`
}

type TaskListRequest struct {
	Token string `form:"token"`
}

type TaskListReply struct {
	BasicReply
	TaskList []Task `json:"task_list"`
}

type TaskInitRequest struct {
	Token string `form:"token"`
}

type TaskInitReply struct {
	BasicReply
	TaskList []Task `json:"task_list"`
}

type DoTaskRequest struct {
	TaskId int64  `form:"task_id"`
	Token  string `form:"token"`
}

type DoTaskReply struct {
	BasicReply
	State int64 `json:"state"`
}

type RankRequest struct {
	Token string `form:"token"`
	Page  int64  `form:"page"`
	Size  int64  `form:"json"`
}

type RankReply struct {
	BasicReply
	Ranklist   []Rank `json:"rank_list"`
	Total_Page int64  `json:"total_page"`
}

type Rank struct {
	Rank      int64  `json:"rank"`
	Id        int64  `json:"id"`
	Name      string `json:"name"`
	AvatarUrl string `json:"avatar_url"`
	Point     int64  `json:"point"`
}

type TaskInfoRequest struct {
	TaskId int64  `form:"task_id"`
	Token  string `form:"token"`
}

type TaskInfoReply struct {
	BasicReply
	Task Task `json:"task"`
}

type AdminTaskInfoRequest struct {
	TaskId int64  `form:"task_id"`
	Token  string `form:"token"`
}

type AdminTaskInfoReply struct {
	BasicReply
	Task Task `json:"task"`
}

type FailTaskListRequest struct {
	Token string `form:"token"`
}

type FailTaskListReply struct {
	BasicReply
	TaskList []Task `json:"task_list"`
}

type AdminCheckTaskRequest struct {
	TaskId     int64  `form:"task_id"`
	ActionType int64  `form:"action_type"`
	Token      string `form:"token"`
}

type AdminCheckTaskReply struct {
	BasicReply
}

type TaskVisualRequest struct {
	Token string `form:"token"`
}

type TaskVisualReply struct {
	BasicReply
}

type RegisterRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
	Collage  string `form:"collage"`
	IdCard   string `form:"id_card"`
}

type RegisterReply struct {
	BasicReply
	UserId int64  `json:"user_id"` //一般用id来在db中找user数据
	Token  string `json:"token"`
}

type LoginRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type LoginReply struct {
	BasicReply
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
}

type AdminLoginRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type AdminLoginReply struct {
	BasicReply
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
}

type GetUserInfoRequest struct {
	UserId int64  `form:"user_id"`
	Token  string `form:"token"`
}

type GetUserInfoReply struct {
	BasicReply
	User User `json:"user"`
}

type UpgradeCharRequest struct {
	Token string `form:"token"`
}

type UpgradeCharReply struct {
	BasicReply
}

type AdminLoadStuRequest struct {
	Token   string    `json:"token"`
	Student []Student `json:"student"`
}

type AdminLoadStuReply struct {
	BasicReply
}

type UserVisualRequest struct {
	Token string `form:"token"`
}

type UserVisualReply struct {
	BasicReply
}
